# Generated by Django 5.1.5 on 2025-02-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocenti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='twitter',
            field=models.CharField(default='No Twitter Link', max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='youtube',
            field=models.CharField(default='No YouTube Link', max_length=255),
        ),
    ]
