# Generated by Django 5.1.5 on 2025-02-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocenti', '0002_alter_signup_twitter_alter_signup_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='twitter',
            field=models.CharField(blank=True, default='No Twitter Link', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='youtube',
            field=models.CharField(blank=True, default='No YouTube Link', max_length=255, null=True),
        ),
    ]
