# Generated by Django 5.1.5 on 2025-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocenti', '0004_alter_signup_email_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='twitter_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='twitter_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='twitter_profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
