# Generated by Django 5.1.5 on 2025-02-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocenti', '0005_signup_twitter_followers_signup_twitter_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='youtube_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='youtube_profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='youtube_subscribers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
