# Generated by Django 5.1.6 on 2025-03-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocenti', '0008_feedback_alter_signup_twitter_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='twitter_followers',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='twitter_last_updated',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='twitter_profile_pic',
        ),
        migrations.AddField(
            model_name='signup',
            name='reddit',
            field=models.CharField(blank=True, default='No Reddit Link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='reddit_account_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='reddit_awards_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='reddit_karma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='reddit_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='reddit_profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='youtube_total_videos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='youtube_total_views',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
