# Generated by Django 5.1.6 on 2025-03-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocenti', '0009_remove_signup_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='reddit_username',
            field=models.CharField(blank=True, default='No Username', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='youtube_channel_name',
            field=models.CharField(blank=True, default='No Username', max_length=255, null=True),
        ),
    ]
