# Generated by Django 5.1.6 on 2025-03-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocenti', '0010_signup_reddit_username_signup_youtube_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='youtube_latest_upload',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
