# Generated by Django 5.1.6 on 2025-03-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocenti', '0011_signup_youtube_latest_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='youtube_latest_upload',
        ),
        migrations.AddField(
            model_name='signup',
            name='youtube_latest_upload_thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='youtube_latest_upload_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='youtube_latest_upload_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
