# Generated by Django 5.1.6 on 2025-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocenti', '0012_remove_signup_youtube_latest_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='reddit_recent_post_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='reddit_recent_post_title',
            field=models.CharField(blank=True, default='No recent post', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='reddit_recent_post_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
